/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
__export(exports, {
  default: () => FileChangeNotifierPlugin
});
var import_obsidian = __toModule(require("obsidian"));
var FileChangeNotifierPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.notificationElement = null;
    this.hideTimeout = null;
  }
  onload() {
    return __async(this, null, function* () {
      console.log("File Change Notifier plugin loaded");
      this.createNotificationBubble();
      this.registerEvent(this.app.vault.on("modify", (file) => {
        this.showNotification();
      }));
    });
  }
  onunload() {
    console.log("File Change Notifier plugin unloaded");
    if (this.notificationElement) {
      this.notificationElement.remove();
      this.notificationElement = null;
    }
    if (this.hideTimeout) {
      clearTimeout(this.hideTimeout);
      this.hideTimeout = null;
    }
  }
  createNotificationBubble() {
    const bubble = document.createElement("div");
    bubble.className = "file-change-bubble";
    bubble.id = "file-change-notifier-bubble";
    bubble.style.cssText = `
			position: fixed;
			bottom: 20px;
			right: 20px;
			width: 12px;
			height: 12px;
			border-radius: 50%;
			background-color: #4f46e5;
			box-shadow: 0 2px 8px rgba(79, 70, 229, 0.3);
			opacity: 0;
			pointer-events: none;
			z-index: 1000;
			transition: opacity 0.3s ease-in-out;
		`;
    document.body.appendChild(bubble);
    this.notificationElement = bubble;
  }
  showNotification() {
    if (!this.notificationElement)
      return;
    if (this.hideTimeout) {
      clearTimeout(this.hideTimeout);
    }
    this.notificationElement.style.opacity = "1";
    this.hideTimeout = setTimeout(() => {
      if (this.notificationElement) {
        this.notificationElement.style.opacity = "0";
      }
      this.hideTimeout = null;
    }, 2e3);
  }
};
