"""Render the portfolio summary as an Obsidian-flavored Markdown note and write
it to the vault. Only ever called on a successful (non-stale) refresh."""
from __future__ import annotations

from pathlib import Path


def _money(v) -> str:
    return "—" if v is None else f"${v:,.2f}"


def _pct(v) -> str:
    return "—" if v is None else f"{v:+.2f}%"


def render_snapshot(p: dict, *, updated: str) -> str:
    lines: list[str] = []
    lines.append("---")
    lines.append("type: portfolio-snapshot")
    lines.append(f"updated: {updated}")
    lines.append("tags: [finance, portfolio, dashboard]")
    lines.append("---")
    lines.append("")
    lines.append("# Portfolio Dashboard")
    lines.append("")
    lines.append("> [!info] Totals")
    lines.append(f"> **Total value:** {_money(p['total_value'])}  ")
    lines.append(f"> **Today:** {_money(p['day_change'])} ({_pct(p.get('day_change_pct'))})  ")
    lines.append(f"> **Unrealized gain:** {_money(p['total_gain'])} ({_pct(p.get('total_gain_pct'))})")
    lines.append("")

    for acct in p["accounts"]:
        broker = f" · {acct['broker']}" if acct["broker"] else ""
        lines.append(f"## {acct['name']}{broker}")
        lines.append("")
        lines.append(f"Value {_money(acct['value'])} · Gain {_money(acct['gain'])} ({_pct(acct.get('gain_pct'))})")
        lines.append("")
        lines.append("| Ticker | Shares | Price | Value | Gain | Gain % |")
        lines.append("|--------|-------:|------:|------:|-----:|-------:|")
        for h in acct["holdings"]:
            if h["error"]:
                lines.append(f"| {h['ticker']} | {h['shares']:g} | ⚠️ | — | — | — |")
            else:
                lines.append(
                    f"| {h['ticker']} | {h['shares']:g} | {_money(h['price'])} | "
                    f"{_money(h['value'])} | {_money(h['gain'])} | {_pct(h['gain_pct'])} |"
                )
        lines.append("")

    lines.append("---")
    lines.append(f"*Machine-generated by life-dashboard on {updated}. Do not edit by hand.*")
    lines.append("")
    return "\n".join(lines)


def write_snapshot(p: dict, path, *, updated: str) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_snapshot(p, updated=updated), encoding="utf-8")
